source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Swift Basics Framework' do
    pod 'Alamofire'
end

target 'Swift_Basics_FrameworkTests' do
  inherit! :search_paths
  # Pods for testing
end
